### ISSUE TITLE
MVP2  Review

### ISSUE THREAD

**Issue by Shaphen** [Shaphen/Badcord#3]
Hello Walker! Please review my first MVP for:

- Allow user view server index
- Ability to create/update new servers (Note: adding photo to server will extend load time significantly)
- Ability to delete servers
- Styling
- And whatever you feel like
-> [Here is a link to my website for your convenience](https://badcord.herokuapp.com/#/) <-

Thanks!

**Comment by samwalker191** [comment]
- [ ] spacing on the server nav bar needs fixing
- [ ] server create form should not be scrollable
- [ ] scroll bar on server nav bar should be hidden
- [ ] make sure all your fonts are matching
- [ ] the little dropdown arrow in the server menu should line up with the server name
- [ ] should disable the button when server is being created to prevent people from clicking i more than once
- [ ] when uploading an icon, it doesnt show up in the server nav bar until refresh.
- [ ]  There should be more space between the server name and the icon upload in the create form
- [ ] you should also only allow image files to be uploaded, i can technically upload any file as an icon right now
